name: the_spot
description: The Spot - A descentralized marketing platform

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  wakelock: ^0.6.2
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.6
  fluttertoast: ^8.0.9
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  dio: ^4.0.6
  firebase_core: ^1.24.0
  firebase_storage: ^10.3.11
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0

  # android only
  flutter_displaymode: ^0.4.0

  # web3 utils
  web3dart: ^2.4.1
  web_socket_channel: ^2.2.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/translations/
    - assets/img/
    - assets/abi.json
